#!/bin/bash

alias reload_aliases="source ~/.bash/aliases"
alias aliases="vim ~/.bash/aliases && reload_aliases"

# General
alias ll='ls -lh'
alias la='ls -A'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias cd..='cd ..'
alias lf="ls -l | egrep -v '^d'"
alias ldir="ls -l | egrep '^d'"
alias ..='cd ..'
alias tree='tree -C'
alias o="open ."
alias m="mate"

# Ack
alias ack="ack --pager='less -FRX'"

# Rails related
alias r="bundle exec rake"
alias rdm="r db:migrate"
alias rdtp="r db:test:prepare"
alias rdmr="r db:migrate:reset"
alias rg="rails generate"
alias rmig="rails generate migration"
alias showgem="BUNDLER_EDITOR=mate bundle open"
alias be="bundle exec"

# GIT related
alias gpr='git pull --rebase'
alias gcm='git checkout master'
alias gl="git log"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cd) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gst="git status"
alias gs="git stash"
alias gsa="git stash apply"
alias gsc="git stash clear"
alias gsp="git stash pop"
alias grc="git rebase --continue"
alias gca="git commit --amend"
alias gf="git rev-parse --abbrev-ref HEAD | sed 's/feature\///' | xargs git flow feature finish"

# security
alias shred="shred -uz -n 9"

# Postgresql
alias pg="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log"

# MySQL
alias mysqlstart='sudo /usr/local/mysql/support-files/mysql.server start'
alias mysqlstop='sudo /usr/local/mysql/support-files/mysql.server stop'

# misc
alias butterfly='butterfly.server.py --unsecure'
